---
resources:
- name: concourse-gp #concourse-common
  type: git
  icon: github
  check_every: 1m
  source:
    uri: https://github.com/liwidev/concourse-test
- name: group-a #imedia-test
  type: git
  icon: github
  check_every: 1m
  source:
    uri: https://github.com/Liwidev/concourse-group-a

jobs:
# update this pipeline before updating child pipelines
- name: set-self
  public: true
  plan:
  - get: group-a #Pull from source imedia-test
    trigger: true
  - get: concourse-gp #Pull from source concourse-common
    trigger: true
  - set_pipeline: self #Set itself
    file: group-a/set-pipelines.yml

- name: set-group-a-pipelines
  public: true
  plan:
  - get: group-a
    trigger: true
    passed: [set-self]
  - get: concourse-gp
    trigger: true
    passed: [set-self]
  - set_pipeline: ms-1-node
    file: concourse-gp/gp-pipelines/node.yml
    var_files:
      - group-a/vars/ms-1-node.yml
  - set_pipeline: ms-1-java
    file: concourse-gp/gp-pipelines/java.yml
  - set_pipeline: ms-2-java
    file: concourse-gp/gp-pipelines/java.yml
  - set_pipeline: ms-3-java
    file: concourse-gp/gp-pipelines/java.yml
  - set_pipeline: rsc-web
    file: concourse-gp/gp-pipelines/java.yml
